# Posprocess word country distribution

## Be able to create selections of keywords and embedding vectors to visualize

In [6]:
import pandas as pd
import re
df=pd.read_csv("words_and_countries.csv")
df.head

<bound method NDFrame.head of        Afghanistan  Albania  Algeria  Argentina  Armenia  Australia  Austria  \
0            106.0      5.0      1.0       11.0      1.0      520.0     55.0
1             68.0      0.0      0.0        5.0      0.0      137.0     16.0
2             29.0      0.0      0.0        4.0      0.0       94.0     20.0
3             23.0      3.0      0.0        6.0      0.0      156.0     13.0
4              9.0      0.0      0.0        1.0      0.0       34.0     13.0
...            ...      ...      ...        ...      ...        ...      ...
23821          0.0      0.0      0.0        0.0      0.0        0.0      0.0
23822          0.0      0.0      0.0        0.0      0.0        0.0      0.0
23823          0.0      0.0      0.0        0.0      0.0        0.0      0.0
23824          0.0      0.0      0.0        0.0      0.0        0.0      0.0
23825          0.0      0.0      0.0        0.0      0.0        0.0      0.0

       Azerbaijan  Bahrain  Bangladesh  ...  Mauritania  Niger  Senegal  \
0             2.0      2.0        23.0  ...         0.0    0.0      0.0
1             0.0      0.0         9.0  ...         0.0    0.0      0.0
2             0.0      0.0        10.0  ...         0.0    0.0      0.0
3             0.0      0.0        13.0  ...         0.0    0.0      0.0
4             0.0      0.0         1.0  ...         0.0    0.0      0.0
...           ...      ...         ...  ...         ...    ...      ...
23821         0.0      0.0         0.0  ...         0.0    0.0      0.0
23822         0.0      0.0         0.0  ...         0.0    0.0      0.0
23823         0.0      0.0         0.0  ...         0.0    0.0      0.0
23824         0.0      0.0         0.0  ...         0.0    0.0      0.0
23825         0.0      0.0         0.0  ...         0.0    0.0      0.0

       Seychelles  Sierra_Leone  Sudan  Togo  n_countries  word_freq  \
0             0.0           0.0    0.0   0.0          136     7339.0
1             0.0           0.0    0.0   0.0          101     2902.0
2             0.0           0.0    0.0   0.0           98     2378.0
3             0.0           0.0    0.0   0.0          103     2287.0
4             0.0           0.0    0.0   0.0           64     2223.0
...           ...           ...    ...   ...          ...        ...
23821         0.0           0.0    0.0   0.0            1        1.0
23822         0.0           0.0    0.0   0.0            1        1.0
23823         0.0           0.0    0.0   0.0            1        1.0
23824         0.0           0.0    0.0   0.0            1        1.0
23825         0.0           0.0    0.0   0.0            1        1.0

                                              words
0                                           suicide
1                                        depression
2                                      risk_factors
3                                         mortality
4                                     united_states
...                                             ...
23821              open_university_of_the_third_age
23822                    psychological_difficulties
23823                                 care_services
23824  serotonin_transporter_linked_promoter_region
23825                                urban_zimbabwe

[23826 rows x 162 columns]>

In [7]:
dfmain=pd.read_csv("Countries_SMR_and_WOS_records.csv")
dfmain.head

<bound method NDFrame.head of     iso2c iso3c              Country              country  WOS_records  \
0      AF   AFG          Afghanistan          Afghanistan          303
1      AL   ALB              Albania              Albania           12
2      DZ   DZA              Algeria              Algeria           11
3      AO   AGO               Angola               Angola            0
4      AG   ATG  Antigua and Barbuda  Antigua_and_Barbuda            0
..    ...   ...                  ...                  ...          ...
178    VE   VEN         Venezuela RB            Venezuela           12
179    VN   VNM             Viet Nam              Vietnam          145
180    YE   YEM           Yemen Rep.                Yemen            6
181    ZM   ZMB               Zambia               Zambia            0
182    ZW   ZWE             Zimbabwe             Zimbabwe           21

    Cluster    Rate  Females_mean  Males_mean  2000_females  ...  \
0       C10     Low         4.060       4.835           4.8  ...
1       C10     Low         4.155       7.545           2.8  ...
2        C9     Low         2.460       4.160           3.4  ...
3        C8  Medium         2.925      11.770           3.3  ...
4        C9     Low         0.220       1.140           0.0  ...
..      ...     ...           ...         ...           ...  ...
178     C10     Low         1.110       5.925           1.5  ...
179     C10     Low         4.440       9.465           4.7  ...
180     C10     Low         4.680       6.930           5.0  ...
181      C7  Medium         5.605      14.895           9.4  ...
182      C7  Medium        13.420      20.000          12.4  ...

     Bin_[100-105)  Bin_[105-110)  Bin_[110-115)  Bin_[115-120)  \
0                0              0              0              0
1                0              0              0              0
2                0              0              0              0
3                0              0              0              0
4                0              0              0              0
..             ...            ...            ...            ...
178              0              0              0              0
179              0              0              0              0
180              0              0              0              0
181              0              0              0              0
182              0              0              0              0

     Bin_[120-125)  Bin_[125-130)  Bin_[130-135)  Bin_[135-140)  \
0                0              0              0              0
1                0              0              0              0
2                0              0              0              0
3                0              0              0              0
4                0              0              0              0
..             ...            ...            ...            ...
178              0              0              0              0
179              0              0              0              0
180              0              0              0              0
181              0              0              0              0
182              0              0              0              0

     Bin_[140-145)  Bin_[145-150)
0                0              0
1                0              0
2                0              0
3                0              0
4                0              0
..             ...            ...
178              0              0
179              0              0
180              0              0
181              0              0
182              0              0

[183 rows x 79 columns]>

In [8]:
l=dfmain.Country.to_list()

In [9]:
c='Russian'
for i,v in enumerate(l):
    if re.search(c,v):
        break;
print(i,v)
print(dfmain.iloc[i].iso2c)

135 Russian Federation
RU

In [10]:
columns=df.columns
print(columns)

Index(['Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       ...
       'Mauritania', 'Niger', 'Senegal', 'Seychelles', 'Sierra_Leone', 'Sudan',
       'Togo', 'n_countries', 'word_freq', 'words'],
      dtype='object', length=162)

In [12]:
import numpy as np

elements=[]

for i in df.index:
    #print(i)
    v=df.iloc[i]
    for j, country in enumerate(columns[:-3]):
        element={}
        element['keyword']=v[-1]
        element['country']=columns[j]
        element['kwd_in_country']=v[j]
        element['kwd_total']=v[-2]
        element['countries_with_kwd']=v[-3]
        elements.append(element) 
        
words_and_countries=pd.DataFrame(elements)

In [13]:
print(words_and_countries.shape)
print(words_and_countries.head)

(3788334, 5)
<bound method NDFrame.head of                 keyword       country  kwd_in_country  kwd_total  \
0               suicide   Afghanistan           106.0     7339.0
1               suicide       Albania             5.0     7339.0
2               suicide       Algeria             1.0     7339.0
3               suicide     Argentina            11.0     7339.0
4               suicide       Armenia             1.0     7339.0
...                 ...           ...             ...        ...
3788329  urban_zimbabwe       Senegal             0.0        1.0
3788330  urban_zimbabwe    Seychelles             0.0        1.0
3788331  urban_zimbabwe  Sierra_Leone             0.0        1.0
3788332  urban_zimbabwe         Sudan             0.0        1.0
3788333  urban_zimbabwe          Togo             0.0        1.0

         countries_with_kwd
0                       136
1                       136
2                       136
3                       136
4                       136
...                     ...
3788329                   1
3788330                   1
3788331                   1
3788332                   1
3788333                   1

[3788334 rows x 5 columns]>

In [14]:
words_and_countries.to_csv("words_and_countries_list.csv", index=False)

## Find keywords only specific to country, where countries with kwd ==1

In [15]:
country_specific_kwds=words_and_countries[ (words_and_countries['countries_with_kwd'] == 1) & (words_and_countries['kwd_in_country'] >0 ) ]  
print(country_specific_kwds.shape)
print( country_specific_kwds.head)

(14315, 5)
<bound method NDFrame.head of                                               keyword        country  \
239777                              western_australia      Australia
323776                       congenital_abnormalities        Hungary
370121                                  iv_audadis_iv  United_States
372965                                      cape_town   South_Africa
379025                            non_hispanic_whites  United_States
...                                               ...            ...
3787555              open_university_of_the_third_age         Brazil
3787756                    psychological_difficulties        Ireland
3787915                                 care_services        Ireland
3788074  serotonin_transporter_linked_promoter_region        Ireland
3788310                                urban_zimbabwe       Zimbabwe

         kwd_in_country  kwd_total  countries_with_kwd
239777             13.0       13.0                   1
323776             10.0       10.0                   1
370121              8.0        8.0                   1
372965              8.0        8.0                   1
379025              8.0        8.0                   1
...                 ...        ...                 ...
3787555             1.0        1.0                   1
3787756             1.0        1.0                   1
3787915             1.0        1.0                   1
3788074             1.0        1.0                   1
3788310             1.0        1.0                   1

[14315 rows x 5 columns]>

In [33]:
N=10
country_specific_kwds_top10=country_specific_kwds.groupby('country').apply(lambda x : x.sort_values(by='kwd_in_country', ascending=False).head(N).reset_index(drop=True))
country_specific_kwds_top10_2=country_specific_kwds.groupby('country').apply(lambda x : x.sort_values(by='kwd_in_country', ascending=False).head(N))

print(country_specific_kwds_top10.head)
country_specific_kwds_top10.to_csv("country_specific_kwds_top10.csv" , index=False)

<bound method NDFrame.head of                                      keyword      country  kwd_in_country  \
country
Afghanistan 0                survey_sampling  Afghanistan             2.0
            1       survey_design_efficiency  Afghanistan             2.0
            2                 sample_weights  Afghanistan             2.0
            3                 design_effects  Afghanistan             2.0
            4  epidemiologic_research_design  Afghanistan             2.0
...                                      ...          ...             ...
Zimbabwe    5              activator_protein     Zimbabwe             1.0
            6                   coenzyme_q10     Zimbabwe             1.0
            7                       hiv_test     Zimbabwe             1.0
            8             lifetime_diagnosis     Zimbabwe             1.0
            9                         harare     Zimbabwe             1.0

               kwd_total  countries_with_kwd
country
Afghanistan 0        2.0                   1
            1        2.0                   1
            2        2.0                   1
            3        2.0                   1
            4        2.0                   1
...                  ...                 ...
Zimbabwe    5        1.0                   1
            6        1.0                   1
            7        1.0                   1
            8        1.0                   1
            9        1.0                   1

[960 rows x 5 columns]>

In [17]:
specific_countries, counts=np.unique(country_specific_kwds['country'] , return_counts=True)
sc=pd.DataFrame({'specific_countries':specific_countries, 'counts':counts}).sort_values(by='counts', ascending=False)
print(sc.head(n=60))
# compute keywords - take first 10 most frequent keywords DONE
sc.to_csv("country_specific_kwd_counts_per_country.csv", index=False)

     specific_countries  counts
122       United_States    2763
53              Ireland    1957
4             Australia     835
22                China     716
57                Japan     644
20               Canada     591
49                India     538
39              Germany     406
112              Sweden     380
37               France     366
55                Italy     267
79          Netherlands     256
117              Turkey     226
108               Spain     224
107         South_Korea     224
29              Denmark     216
36              Finland     210
15               Brazil     192
106        South_Africa     181
71               Mexico     177
113         Switzerland     171
54               Israel     168
51                 Iran     167
121      United_Kingdom     160
84               Norway     138
43               Guinea     129
52                 Iraq     111
109           Sri_Lanka      93
10              Belgium      93
47              Hungary      88
91               Poland      75
126             Vietnam      74
5               Austria      73
86             Pakistan      69
41               Greece      61
94              Romania      57
102           Singapore      57
68             Malaysia      51
82              Nigeria      47
21                Chile      46
25              Croatia      46
40                Ghana      43
104            Slovenia      41
95   Russian_Federation      39
0           Afghanistan      36
23             Colombia      36
66            Lithuania      34
118              Uganda      33
8            Bangladesh      33
92             Portugal      29
115            Thailand      28
34             Ethiopia      28
78                Nepal      27
50            Indonesia      26
100              Serbia      22
60                Kenya      21
81                Niger      21
63              Lebanon      20
48              Iceland      20
98         Saudi_Arabia      20

## Filter the embedding vectors and keywords according to country

In [18]:
metadata=pd.read_csv("metadata_trained_with_keywords.tsv", sep='\t', header=None, names=['keyword'])
n=['d'+str(x+1) for x in range(300)]
vectors=pd.read_csv("vectors_trained_with_keywords.tsv", sep='\t', header=None, names=n)

In [19]:
len(metadata)

23826

In [20]:
vectors.shape

(23826, 300)

In [22]:
metadata.tail(n=20)

                           keyword
23806   16_and_17_year_old_drivers
23807                       160_mg
23808      15_year_old_adolescents
23809           15_european_cities
23810            14_year_follow_up
23811            13_year_follow_up
23812  13_cis_retinoic_acid_alters
23813                 13_butadiene
23814  12_task_of_financial_reform
23815            12_month_outcomes
23816                 11th_version
23817            11_year_follow_up
23818      11_european_populations
23819            10_year_mortality
23820               10_year_course
23821                           10
23822          0000_0002_7629_6579
23823          0000_0001_5375_3565
23824                          000
23825                            +

In [25]:
md=metadata["keyword"].to_list()
#md.insert(0,"0")
len(md)

23826

In [26]:
vectors["keyword"]=md
vectors.head(n=2)

,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,...,d292,d293,d294,d295,d296,d297,d298,d299,d300,keyword
0,-0.005096,0.038734,0.001277,0.011998,-0.039178,0.008123,-0.034907,0.002304,-0.006959,-0.026078,...,0.007628,-0.034966,-0.026773,-0.016370,-0.031015,0.045697,0.019724,-0.006399,0.018297,[UNK]
1,-0.047337,-0.027880,-0.030139,0.003591,-0.030996,-0.022267,-0.004555,0.064699,-0.004952,-0.005174,...,0.077549,0.096544,-0.069497,-0.045825,0.036648,-0.032877,0.054365,0.055177,0.107828,suicide

### Select keywords for a specific country and by these keywords select the embedding vectors
##### Use country_specific_kwds_top10 . To each row add embedding vectors and additional information from dfmain about the clusters.

In [27]:
print(country_specific_kwds_top10.index[0][1])

0

In [28]:
n=['keyword']+['d'+str(x+1) for x in range(300)]

In [29]:
import json
file='embedded_vectors_trained_with_keywords.json'

#with open(file, 'w') as f: 
#    json.dump(embedded_vectors, f)

# How to read it from json file
with open(file, 'r') as f:
    embedded_vectors = json.load(f)

embedded_vectors_df=pd.DataFrame(embedded_vectors).T.reset_index()

In [30]:
embedded_vectors_df.columns=n
embedded_vectors_df.head

<bound method NDFrame.head of                    keyword        d1        d2        d3        d4        d5  \
0                    [UNK] -0.005096  0.038734  0.001277  0.011998 -0.039178
1                  suicide -0.047337 -0.027880 -0.030139  0.003591 -0.030996
2               depression  0.066489  0.067822 -0.069819 -0.008472  0.020755
3             risk_factors -0.006899  0.054188  0.001828  0.042543  0.017842
4                mortality -0.021221 -0.005894 -0.023540  0.004677 -0.036245
...                    ...       ...       ...       ...       ...       ...
23821                   10 -0.071988  0.012133 -0.023012 -0.049081  0.013932
23822  0000_0002_7629_6579  0.015432  0.053198 -0.047108  0.015916 -0.000819
23823  0000_0001_5375_3565  0.013897  0.041775  0.011251  0.027889 -0.015892
23824                  000  0.046669 -0.002860  0.029328  0.031477 -0.050368
23825                    + -0.039551 -0.015243  0.033839  0.036279 -0.005864

             d6        d7        d8        d9  ...      d291      d292  \
0      0.008123 -0.034907  0.002304 -0.006959  ... -0.045848  0.007628
1     -0.022267 -0.004555  0.064699 -0.004952  ...  0.018585  0.077549
2      0.014108  0.017859  0.040247 -0.045830  ... -0.053172  0.006779
3     -0.125632  0.127055  0.014829  0.035088  ...  0.001133 -0.038643
4     -0.044037  0.007062  0.060710  0.088595  ... -0.043798 -0.026470
...         ...       ...       ...       ...  ...       ...       ...
23821  0.026360  0.042763 -0.010678 -0.033877  ... -0.057849 -0.056908
23822  0.026487 -0.021132 -0.016230 -0.051456  ... -0.014975 -0.004422
23823 -0.052342 -0.048859  0.041560  0.016401  ...  0.044577  0.015055
23824  0.018178  0.007830 -0.015583  0.001081  ... -0.029022  0.057958
23825  0.027015  0.003927 -0.019531 -0.006503  ...  0.009868 -0.002098

           d293      d294      d295      d296      d297      d298      d299  \
0     -0.034966 -0.026773 -0.016370 -0.031015  0.045697  0.019724 -0.006399
1      0.096544 -0.069497 -0.045825  0.036648 -0.032877  0.054365  0.055177
2     -0.003414  0.049721 -0.036329 -0.011008 -0.041204 -0.005684  0.123273
3      0.065845 -0.029083 -0.099665 -0.044828  0.029137  0.007554 -0.005553
4      0.040710 -0.040239  0.078818 -0.022044 -0.092706 -0.096192 -0.009331
...         ...       ...       ...       ...       ...       ...       ...
23821  0.057596 -0.058068  0.007754  0.024402 -0.021185 -0.050028  0.022087
23822 -0.054576 -0.000370  0.009054  0.015702  0.001448 -0.016296 -0.027079
23823 -0.009585  0.030770 -0.022419 -0.065711  0.016844 -0.011410  0.063084
23824 -0.063539 -0.003890 -0.034854  0.055157  0.042456 -0.013616  0.010405
23825 -0.048680  0.056597 -0.017193 -0.009544 -0.013915 -0.009595 -0.004595

           d300
0      0.018297
1      0.107828
2     -0.032182
3     -0.082961
4      0.056752
...         ...
23821  0.005017
23822  0.056892
23823 -0.006888
23824 -0.056039
23825 -0.029944

[23826 rows x 301 columns]>

#### Join on keyword and them with cluster matrix information join on country

In [32]:
clust_info=dfmain
clust_cols=clust_info[["iso3c","WOS_records","Cluster","Rate","Females_mean","Males_mean","Country","country"]]
print(clust_cols.head)

<bound method NDFrame.head of     iso3c  WOS_records Cluster    Rate  Females_mean  Males_mean  \
0     AFG          303     C10     Low         4.060       4.835
1     ALB           12     C10     Low         4.155       7.545
2     DZA           11      C9     Low         2.460       4.160
3     AGO            0      C8  Medium         2.925      11.770
4     ATG            0      C9     Low         0.220       1.140
..    ...          ...     ...     ...           ...         ...
178   VEN           12     C10     Low         1.110       5.925
179   VNM          145     C10     Low         4.440       9.465
180   YEM            6     C10     Low         4.680       6.930
181   ZMB            0      C7  Medium         5.605      14.895
182   ZWE           21      C7  Medium        13.420      20.000

                 Country              country
0            Afghanistan          Afghanistan
1                Albania              Albania
2                Algeria              Algeria
3                 Angola               Angola
4    Antigua and Barbuda  Antigua_and_Barbuda
..                   ...                  ...
178         Venezuela RB            Venezuela
179             Viet Nam              Vietnam
180           Yemen Rep.                Yemen
181               Zambia               Zambia
182             Zimbabwe             Zimbabwe

[183 rows x 8 columns]>

In [34]:
import io
import array

# for keyword in each line find a corresponding embedded vector and write it to file 
cp=country_specific_kwds_top10_2.copy().reset_index(drop=True, allow_duplicates=True)

cp.drop(columns=['kwd_total', 'countries_with_kwd'])
print(cp.head)

<bound method NDFrame.head of                            keyword      country  kwd_in_country  kwd_total  \
0                  survey_sampling  Afghanistan             2.0        2.0
1         survey_design_efficiency  Afghanistan             2.0        2.0
2                   sample_weights  Afghanistan             2.0        2.0
3                   design_effects  Afghanistan             2.0        2.0
4    epidemiologic_research_design  Afghanistan             2.0        2.0
..                             ...          ...             ...        ...
955              activator_protein     Zimbabwe             1.0        1.0
956                   coenzyme_q10     Zimbabwe             1.0        1.0
957                       hiv_test     Zimbabwe             1.0        1.0
958             lifetime_diagnosis     Zimbabwe             1.0        1.0
959                         harare     Zimbabwe             1.0        1.0

     countries_with_kwd
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
955                   1
956                   1
957                   1
958                   1
959                   1

[960 rows x 5 columns]>

In [35]:
# join data frames
cp1=pd.merge(left=cp, right=embedded_vectors_df, on='keyword')
country_specific_keywords_and_vectors=pd.merge(left=cp1, right=clust_cols, on='country')

In [22]:
print(country_specific_keywords_and_vectors.head)
country_specific_keywords_and_vectors.to_csv("country_specific_keywords_and_vectors.csv", index=False)
print(country_specific_keywords_and_vectors.columns)

<bound method NDFrame.head of                            keyword      country  kwd_in_country  kwd_total  \
0                  survey_sampling  Afghanistan             2.0        2.0
1                   sample_weights  Afghanistan             2.0        2.0
2    epidemiologic_research_design  Afghanistan             2.0        2.0
3                   design_effects  Afghanistan             2.0        2.0
4                      sample_bias  Afghanistan             2.0        2.0
..                             ...          ...             ...        ...
979                 urban_zimbabwe     Zimbabwe             1.0        1.0
980                       hiv_test     Zimbabwe             1.0        1.0
981                       saposinb     Zimbabwe             1.0        1.0
982              activator_protein     Zimbabwe             1.0        1.0
983                   coenzyme_q10     Zimbabwe             1.0        1.0

     countries_with_kwd        d1        d2        d3        d4        d5  \
0                     1  0.023013 -0.040507 -0.022095 -0.019781 -0.050438
1                     1 -0.005720 -0.000229 -0.008355  0.000177  0.017858
2                     1 -0.004561  0.012203  0.026331 -0.002290 -0.000273
3                     1  0.035445 -0.007295  0.032871 -0.073507  0.006853
4                     1  0.071154 -0.036695 -0.008129  0.010533  0.043105
..                  ...       ...       ...       ...       ...       ...
979                   1  0.010256  0.063302 -0.001765 -0.024302 -0.098545
980                   1 -0.080140  0.024504  0.066768  0.056089  0.016085
981                   1  0.014438  0.034001  0.056112 -0.000138 -0.034110
982                   1  0.010689  0.045069  0.038648 -0.027492 -0.071192
983                   1 -0.079800 -0.021987 -0.024806 -0.046739  0.044848

     ...      d298      d299      d300  iso3c  WOS_records  Cluster    Rate  \
0    ... -0.033116 -0.000831  0.012711    AFG          303      C10     Low
1    ... -0.000389  0.003725 -0.058521    AFG          303      C10     Low
2    ...  0.058954  0.010507  0.050396    AFG          303      C10     Low
3    ...  0.003465  0.031745  0.042098    AFG          303      C10     Low
4    ... -0.018657  0.024590  0.015478    AFG          303      C10     Low
..   ...       ...       ...       ...    ...          ...      ...     ...
979  ... -0.010278  0.023456  0.029562    ZWE           21       C7  Medium
980  ... -0.111073 -0.016565 -0.062831    ZWE           21       C7  Medium
981  ...  0.029424  0.010344 -0.007373    ZWE           21       C7  Medium
982  ... -0.061438 -0.015700  0.008969    ZWE           21       C7  Medium
983  ... -0.039676  0.014899 -0.044827    ZWE           21       C7  Medium

     Females_mean  Males_mean      Country
0            4.06       4.835  Afghanistan
1            4.06       4.835  Afghanistan
2            4.06       4.835  Afghanistan
3            4.06       4.835  Afghanistan
4            4.06       4.835  Afghanistan
..            ...         ...          ...
979         13.42      20.000     Zimbabwe
980         13.42      20.000     Zimbabwe
981         13.42      20.000     Zimbabwe
982         13.42      20.000     Zimbabwe
983         13.42      20.000     Zimbabwe

[984 rows x 312 columns]>
Index(['keyword', 'country', 'kwd_in_country', 'kwd_total',
       'countries_with_kwd', 'd1', 'd2', 'd3', 'd4', 'd5',
       ...
       'd298', 'd299', 'd300', 'iso3c', 'WOS_records', 'Cluster', 'Rate',
       'Females_mean', 'Males_mean', 'Country'],
      dtype='object', length=312)

In [23]:
cnames=pd.unique(country_specific_keywords_and_vectors["Cluster"])
for cname in cnames:
    fname=cname+"_COUNTRY_SPECIFIC_KEYWORDS.csv"
    cdf=country_specific_keywords_and_vectors[country_specific_keywords_and_vectors["Cluster"]==cname]
    print(fname, cdf.shape)
    cdf.to_csv(fname, index=False)

C10_COUNTRY_SPECIFIC_KEYWORDS.csv (254, 312)
C9_COUNTRY_SPECIFIC_KEYWORDS.csv (94, 312)
C8_COUNTRY_SPECIFIC_KEYWORDS.csv (237, 312)
C7_COUNTRY_SPECIFIC_KEYWORDS.csv (170, 312)
C6_COUNTRY_SPECIFIC_KEYWORDS.csv (94, 312)
C5_COUNTRY_SPECIFIC_KEYWORDS.csv (45, 312)
C2_COUNTRY_SPECIFIC_KEYWORDS.csv (83, 312)
C4_COUNTRY_SPECIFIC_KEYWORDS.csv (7, 312)

### Now work with keywords shared by countries

In [24]:
country_shared_kwds=words_and_countries[ (words_and_countries['countries_with_kwd'] > 1) & (words_and_countries['kwd_in_country'] >0 ) ]  
print(country_shared_kwds.shape)
print( country_shared_kwds.head)

(57124, 5)
<bound method NDFrame.head of                     keyword      country  kwd_in_country  kwd_total  \
0                   suicide  Afghanistan           105.0     7335.0
1                   suicide      Albania             5.0     7335.0
2                   suicide      Algeria             1.0     7335.0
3                   suicide    Argentina            11.0     7335.0
4                   suicide      Armenia             1.0     7335.0
...                     ...          ...             ...        ...
1691097            robotics         Iraq             1.0        2.0
1691196               fkbp5  Afghanistan             1.0        2.0
1691253               fkbp5         Iraq             1.0        2.0
1691508  precision_medicine  Afghanistan             1.0        2.0
1691565  precision_medicine         Iraq             1.0        2.0

         countries_with_kwd
0                       137
1                       137
2                       137
3                       137
4                       137
...                     ...
1691097                   2
1691196                   2
1691253                   2
1691508                   2
1691565                   2

[57124 rows x 5 columns]>

### Work with keywords specific to countries
### Add economy and region.

In [ ]:
# read the main data matrix
#words=country_specific_kwds[ country_specific_kwds['country']==scountry ].keyword.to_list()
#print(sc.specific_countries.to_list() )
#print(words)

In [151]:
'''
import io
import array


for scountry in sc.specific_countries.to_list():    
    words=country_specific_kwds[ country_specific_kwds['country']==scountry ].keyword.to_list()
    
    # this is list of embedding vectors  
    
    out_v = io.open('embedding_projector1/'+scountry+'_vectors.tsv', 'w', encoding='utf-8')
    out_m = io.open('embedding_projector1/'+scountry+'_metadata.tsv', 'w', encoding='utf-8')

    word_subset=[]
    vect_subset=np.empty((len(words),300))
    j=0
    for word in words:
        vec=embedded_vectors[word]
        out_v.write('\t'.join([str(x) for x in vec]) + "\n")
        out_m.write(word + "\n")
        word_subset.append(word)
        vect_subset[j]=np.array(vec)
        j+=1
    
    out_v.close()
    out_m.close()
'''

In [146]:
'''
import io
import array


for scountry in sc.specific_countries.to_list():    
    words=country_specific_kwds[ country_specific_kwds['country']==scountry ].keyword.to_list()
    
    # this is list of embedding vectors  
    
    out_v = io.open('embedding_projector/'+mscountry+'_vectors.tsv', 'w', encoding='utf-8')
    out_m = io.open('embedding_projector/'+scountry+'_metadata.tsv', 'w', encoding='utf-8')
    
    j=0
    for index, word in enumerate(vocab):
      #print(word)  
      if index == 0:
        continue  # skip 0, it's padding.
      if word in words:
        #print(word)
        vec = weights.iloc[index].to_numpy()
        #print(vec)
        out_v.write('\t'.join([str(x) for x in vec]) + "\n")
        out_m.write(word + "\n")
        word_subset.append(word)
        vect_subset[j]=vec
        j+=1
    
    out_v.close()
    out_m.close()
'''

In [123]:
#print(vect_subset.shape)

(3099, 300)

### UMAP

In [140]:
'''
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import umap

reducer=umap.UMAP( n_components=3, n_neighbors=15, repulsion_strength=1)

embedding = reducer.fit_transform(vect_subset)

#embedding = reducer.fit_transform(scaled_data)
print(embedding.shape)
'''

(902, 3)

### Visualize

In [25]:
'''
plt.scatter(
    embedding[:, 0],
    embedding[:, 1])
#    c=actual)

#c=[sns.color_palette()[x] for x in penguins.species.map({"Adelie":0, "Chinstrap":1, "Gentoo":2})]

plt.gca().set_aspect('equal', 'datalim')
plt.title('UMAP projection of word embedding', fontsize=24);
'''

'\nplt.scatter(\n    embedding[:, 0],\n    embedding[:, 1])\n#    c=actual)\n\n#c=[sns.color_palette()[x] for x in penguins.species.map({"Adelie":0, "Chinstrap":1, "Gentoo":2})]\n\nplt.gca().set_aspect(\'equal\', \'datalim\')\nplt.title(\'UMAP projection of word embedding\', fontsize=24);\n'

### Filter keywords shared between countries

In [152]:
country_shared_kwds=words_and_countries[ (words_and_countries['countries_with_kwd'] > 1) & (words_and_countries['kwd_in_country'] >0 ) ]  
print(country_shared_kwds.shape)
print( country_shared_kwds.head)

(57124, 5)
<bound method NDFrame.head of                     keyword      country  kwd_in_country  kwd_total  \
0                   suicide  Afghanistan           105.0     7335.0
1                   suicide      Albania             5.0     7335.0
2                   suicide      Algeria             1.0     7335.0
3                   suicide    Argentina            11.0     7335.0
4                   suicide      Armenia             1.0     7335.0
...                     ...          ...             ...        ...
1691097            robotics         Iraq             1.0        2.0
1691196               fkbp5  Afghanistan             1.0        2.0
1691253               fkbp5         Iraq             1.0        2.0
1691508  precision_medicine  Afghanistan             1.0        2.0
1691565  precision_medicine         Iraq             1.0        2.0

         countries_with_kwd
0                       137
1                       137
2                       137
3                       137
4                       137
...                     ...
1691097                   2
1691196                   2
1691253                   2
1691508                   2
1691565                   2

[57124 rows x 5 columns]>

### Filter most common and frequent keywords out

In [154]:
!cat frequent_words_to_filter

suicide
risk
prevalence
mortality
adolescents
depression
ideation
risk_factors
behavior
mental_health
health
epidemiology
gender
trends
children
rates
prevention
disorders
countries
violence
youth
women
suicidal_ideation
population
association
death
alcohol
care
impact
gender_differences
attitudes
symptoms
people
homicide
united_states

In [155]:
words_to_filter_out=["suicide","risk","prevalence","mortality","adolescents","depression","ideation","risk_factors","behavior","mental_health",
                     "health","epidemiology","gender","trends","children","rates","prevention","disorders","countries","violence",
                     "youth","women","suicidal_ideation","population","association","death","alcohol","care","impact","gender_differences",
                     "attitudes","symptoms","people","homicide","united_states"]

In [158]:
country_shared_kwds['keyword']

0                     suicide
1                     suicide
2                     suicide
3                     suicide
4                     suicide
                  ...
1691097              robotics
1691196                 fkbp5
1691253                 fkbp5
1691508    precision_medicine
1691565    precision_medicine
Name: keyword, Length: 57124, dtype: object

In [159]:
country_shared_kwds_filtered=country_shared_kwds[ ~country_shared_kwds.keyword.isin(words_to_filter_out)]
print(country_shared_kwds_filtered.shape)
print(country_shared_kwds_filtered.head)

(54171, 5)
<bound method NDFrame.head of                     keyword                 country  kwd_in_country  \
2497             euthanasia                 Albania             1.0
2501             euthanasia               Australia            45.0
2502             euthanasia                 Austria             5.0
2508             euthanasia                 Belgium           125.0
2511             euthanasia  Bosnia_and_Herzegovina             1.0
...                     ...                     ...             ...
1691097            robotics                    Iraq             1.0
1691196               fkbp5             Afghanistan             1.0
1691253               fkbp5                    Iraq             1.0
1691508  precision_medicine             Afghanistan             1.0
1691565  precision_medicine                    Iraq             1.0

         kwd_total  countries_with_kwd
2497         975.0                  44
2501         975.0                  44
2502         975.0                  44
2508         975.0                  44
2511         975.0                  44
...            ...                 ...
1691097        2.0                   2
1691196        2.0                   2
1691253        2.0                   2
1691508        2.0                   2
1691565        2.0                   2

[54171 rows x 5 columns]>

In [182]:
country_shared_kwds_filtered.to_csv("country_shared_kwds_filtered.csv", index=False)

### Very large amount of information, sort and retain only 10 countries having the highest number of keyword occurrences

In [186]:
# pandas dataframe group by keyword, sort by keyword in country, retain 10 countries with most frquent word
country_shared_kwds_filtered_reduced = country_shared_kwds_filtered.sort_values(['kwd_total','kwd_in_country'],ascending = False).groupby('keyword').head(5)
print(country_shared_kwds_filtered_reduced.head)
print(country_shared_kwds_filtered_reduced.shape)

<bound method NDFrame.head of                     keyword        country  kwd_in_country  kwd_total  \
2582             euthanasia    Netherlands           295.0      975.0
2508             euthanasia        Belgium           125.0      975.0
2625             euthanasia  United_States            96.0      975.0
2517             euthanasia         Canada            88.0      975.0
2613             euthanasia    Switzerland            85.0      975.0
...                     ...            ...             ...        ...
1691097            robotics           Iraq             1.0        2.0
1691196               fkbp5    Afghanistan             1.0        2.0
1691253               fkbp5           Iraq             1.0        2.0
1691508  precision_medicine    Afghanistan             1.0        2.0
1691565  precision_medicine           Iraq             1.0        2.0

         countries_with_kwd
2582                     44
2508                     44
2625                     44
2517                     44
2613                     44
...                     ...
1691097                   2
1691196                   2
1691253                   2
1691508                   2
1691565                   2

[32565 rows x 5 columns]>
(32565, 5)

In [187]:
country_shared_kwds_filtered_reduced.to_csv("country_shared_kwds_filtered_reduced.csv", index=False)

In [183]:
countries=np.unique(country_shared_kwds_filtered.country).tolist()
keywords=np.unique(country_shared_kwds_filtered.keyword).tolist()
labelc=['country']*len(countries)
labelk=['keyword']*len(keywords)

nodes=pd.DataFrame({'node':countries+keywords, 'type':labelc+labelk})
print(nodes.head)
nodes.to_csv("nodes1.csv", index=False)

#NODES WERE MODIFIED

<bound method NDFrame.head of               node     type
0      Afghanistan  country
1          Albania  country
2          Algeria  country
3        Argentina  country
4          Armenia  country
...            ...      ...
10047     zimbabwe  keyword
10048      zip_gun  keyword
10049       zodiac  keyword
10050     zolpidem  keyword
10051     zongjiao  keyword

[10052 rows x 2 columns]>

### Read the data matrix with cluster information

In [175]:
clust_info=pd.read_csv('~/JUDITA/mdpi_sustainability/Final_datasets/Countries_suicide_rates_and_WOS_records.csv')
print(clust_info.head)

<bound method NDFrame.head of     iso2c iso3c              Country  WOS_records Cluster    Rate  \
0      AF   AFG          Afghanistan          303     C10     Low
1      AL   ALB              Albania           12     C10     Low
2      DZ   DZA              Algeria           11      C9     Low
3      AO   AGO               Angola            0      C8  Medium
4      AG   ATG  Antigua and Barbuda            0      C9     Low
..    ...   ...                  ...          ...     ...     ...
178    VE   VEN        Venezuela, RB           12     C10     Low
179    VN   VNM             Viet Nam          145     C10     Low
180    YE   YEM          Yemen, Rep.            6     C10     Low
181    ZM   ZMB               Zambia            0      C7  Medium
182    ZW   ZWE             Zimbabwe           21      C7  Medium

     Females_mean  Males_mean  2000_females  2001_females  ...  Bin_[100-105)  \
0           4.060       4.835           4.8           4.8  ...              0
1           4.155       7.545           2.8           2.9  ...              0
2           2.460       4.160           3.4           3.4  ...              0
3           2.925      11.770           3.3           3.2  ...              0
4           0.220       1.140           0.0           0.0  ...              0
..            ...         ...           ...           ...  ...            ...
178         1.110       5.925           1.5           1.7  ...              0
179         4.440       9.465           4.7           4.6  ...              0
180         4.680       6.930           5.0           5.0  ...              0
181         5.605      14.895           9.4           8.6  ...              0
182        13.420      20.000          12.4          11.3  ...              0

     Bin_[105-110)  Bin_[110-115)  Bin_[115-120)  Bin_[120-125)  \
0                0              0              0              0
1                0              0              0              0
2                0              0              0              0
3                0              0              0              0
4                0              0              0              0
..             ...            ...            ...            ...
178              0              0              0              0
179              0              0              0              0
180              0              0              0              0
181              0              0              0              0
182              0              0              0              0

     Bin_[125-130)  Bin_[130-135)  Bin_[135-140)  Bin_[140-145)  Bin_[145-150)
0                0              0              0              0              0
1                0              0              0              0              0
2                0              0              0              0              0
3                0              0              0              0              0
4                0              0              0              0              0
..             ...            ...            ...            ...            ...
178              0              0              0              0              0
179              0              0              0              0              0
180              0              0              0              0              0
181              0              0              0              0              0
182              0              0              0              0              0

[183 rows x 78 columns]>

In [178]:
for country in countries:
    print(country)
    if country in clust_info.Country:
        print("exists")
    else:
        print("not exists")

Afghanistan
not exists
Albania
not exists
Algeria
not exists
Argentina
not exists
Armenia
not exists
Australia
not exists
Austria
not exists
Azerbaijan
not exists
Bahamas
not exists
Bahrain
not exists
Bangladesh
not exists
Barbados
not exists
Belarus
not exists
Belgium
not exists
Benin
not exists
Bhutan
not exists
Bolivia
not exists
Bosnia_and_Herzegovina
not exists
Brazil
not exists
Brunei_Darussalam
not exists
Bulgaria
not exists
Burkina_Faso
not exists
Cambodia
not exists
Cameroon
not exists
Canada
not exists
Central_African_Republic
not exists
Chad
not exists
Chile
not exists
China
not exists
Colombia
not exists
Congo
not exists
Congo_Democratic_Republic
not exists
Costa_Rica
not exists
Croatia
not exists
Cuba
not exists
Cyprus
not exists
Czechia
not exists
Denmark
not exists
Dominican_Republic
not exists
Ecuador
not exists
Egypt
not exists
El_Salvador
not exists
Eritrea
not exists
Estonia
not exists
Ethiopia
not exists
Fiji
not exists
Finland
not exists
France
not exists
Gambia
not exists
Georgia
not exists
Germany
not exists
Ghana
not exists
Greece
not exists
Guatemala
not exists
Guinea
not exists
Guinea-Bissau
not exists
Guyana
not exists
Haiti
not exists
Honduras
not exists
Hungary
not exists
Iceland
not exists
India
not exists
Indonesia
not exists
Iran
not exists
Iraq
not exists
Ireland
not exists
Israel
not exists
Italy
not exists
Jamaica
not exists
Japan
not exists
Jordan
not exists
Kazakhstan
not exists
Kenya
not exists
Kiribati
not exists
Kuwait
not exists
Latvia
not exists
Lebanon
not exists
Liberia
not exists
Libya
not exists
Lithuania
not exists
Luxembourg
not exists
Madagascar
not exists
Malawi
not exists
Malaysia
not exists
Mali
not exists
Malta
not exists
Mauritania
not exists
Mexico
not exists
Micronesia
not exists
Moldova
not exists
Mongolia
not exists
Montenegro
not exists
Morocco
not exists
Mozambique
not exists
Myanmar
not exists
Namibia
not exists
Nepal
not exists
Netherlands
not exists
Nicaragua
not exists
Niger
not exists
Nigeria
not exists
North_Korea
not exists
Norway
not exists
Oman
not exists
Pakistan
not exists
Panama
not exists
Papua_New_Guinea
not exists
Paraguay
not exists
Peru
not exists
Philippines
not exists
Poland
not exists
Portugal
not exists
Qatar
not exists
Romania
not exists
Russian_Federation
not exists
Rwanda
not exists
Samoa
not exists
Saudi_Arabia
not exists
Senegal
not exists
Serbia
not exists
Seychelles
not exists
Sierra_Leone
not exists
Singapore
not exists
Slovak_Republic
not exists
Slovenia
not exists
Solomon_Islands
not exists
Somalia
not exists
South_Africa
not exists
South_Korea
not exists
Spain
not exists
Sri_Lanka
not exists
St_Vincent_Grenadines
not exists
Sudan
not exists
Suriname
not exists
Sweden
not exists
Switzerland
not exists
Syria
not exists
Tajikistan
not exists
Tanzania
not exists
Thailand
not exists
Togo
not exists
Tonga
not exists
Trinidad_and_Tobago
not exists
Turkey
not exists
Uganda
not exists
Ukraine
not exists
United_Arab_Emirates
not exists
United_Kingdom
not exists
United_States
not exists
Uruguay
not exists
Uzbekistan
not exists
Vanuatu
not exists
Venezuela
not exists
Vietnam
not exists
Yemen
not exists
Zimbabwe
not exists

In [180]:
for country in clust_info.Country:
    print(country)
    if country in countries:
        print("exists")
    else:
        print("NOT EXISTS")

Afghanistan
exists
Albania
exists
Algeria
exists
Angola
NOT EXISTS
Antigua and Barbuda
NOT EXISTS
Argentina
exists
Armenia
exists
Australia
exists
Austria
exists
Azerbaijan
exists
Bahamas
exists
Bahrain
exists
Bangladesh
exists
Barbados
exists
Belarus
exists
Belgium
exists
Belize
NOT EXISTS
Benin
exists
Bhutan
exists
Bolivia
exists
Bosnia and Herzegovina
NOT EXISTS
Botswana
NOT EXISTS
Brazil
exists
Brunei Darussalam
NOT EXISTS
Bulgaria
exists
Burkina Faso
NOT EXISTS
Burundi
NOT EXISTS
Cabo Verde
NOT EXISTS
Cambodia
exists
Cameroon
exists
Canada
exists
Central African Republic
NOT EXISTS
Chad
exists
Chile
exists
China
exists
Colombia
exists
Comoros
NOT EXISTS
Congo, Dem. Rep.
NOT EXISTS
Congo, Rep.
NOT EXISTS
Costa Rica
NOT EXISTS
Cote d'Ivoire
NOT EXISTS
Croatia
exists
Cuba
exists
Cyprus
exists
Czechia
exists
Denmark
exists
Djibouti
NOT EXISTS
Dominican Republic
NOT EXISTS
Ecuador
exists
Egypt, Arab Rep.
NOT EXISTS
El Salvador
NOT EXISTS
Equatorial Guinea
NOT EXISTS
Eritrea
exists
Estonia
exists
Eswatini
NOT EXISTS
Ethiopia
exists
Fiji
exists
Finland
exists
France
exists
Gabon
NOT EXISTS
Gambia
exists
Georgia
exists
Germany
exists
Ghana
exists
Greece
exists
Grenada
NOT EXISTS
Guatemala
exists
Guinea
exists
Guinea-Bissau
exists
Guyana
exists
Haiti
exists
Honduras
exists
Hungary
exists
Iceland
exists
India
exists
Indonesia
exists
Iran, Islamic Rep.
NOT EXISTS
Iraq
exists
Ireland
exists
Israel
exists
Italy
exists
Jamaica
exists
Japan
exists
Jordan
exists
Kazakhstan
exists
Kenya
exists
Kiribati
exists
Korea, Dem. People's Rep.
NOT EXISTS
Korea, Rep.
NOT EXISTS
Kuwait
exists
Kyrgyz Republic
NOT EXISTS
Lao PDR
NOT EXISTS
Latvia
exists
Lebanon
exists
Lesotho
NOT EXISTS
Liberia
exists
Libya
exists
Lithuania
exists
Luxembourg
exists
Madagascar
exists
Malawi
exists
Malaysia
exists
Maldives
NOT EXISTS
Mali
exists
Malta
exists
Mauritania
exists
Mauritius
NOT EXISTS
Mexico
exists
Micronesia, Fed. Sts.
NOT EXISTS
Moldova
exists
Mongolia
exists
Montenegro
exists
Morocco
exists
Mozambique
exists
Myanmar
exists
Namibia
exists
Nepal
exists
Netherlands
exists
New Zealand
NOT EXISTS
Nicaragua
exists
Niger
exists
Nigeria
exists
North Macedonia
NOT EXISTS
Norway
exists
Oman
exists
Pakistan
exists
Panama
exists
Papua New Guinea
NOT EXISTS
Paraguay
exists
Peru
exists
Philippines
exists
Poland
exists
Portugal
exists
Qatar
exists
Romania
exists
Russian Federation
NOT EXISTS
Rwanda
exists
Samoa
exists
Sao Tome and Principe
NOT EXISTS
Saudi Arabia
NOT EXISTS
Senegal
exists
Serbia
exists
Seychelles
exists
Sierra Leone
NOT EXISTS
Singapore
exists
Slovak Republic
NOT EXISTS
Slovenia
exists
Solomon Islands
NOT EXISTS
Somalia
exists
South Africa
NOT EXISTS
South Sudan
NOT EXISTS
Spain
exists
Sri Lanka
NOT EXISTS
St. Lucia
NOT EXISTS
St. Vincent and the Grenadines
NOT EXISTS
Sudan
exists
Suriname
exists
Sweden
exists
Switzerland
exists
Syrian Arab Republic
NOT EXISTS
Tajikistan
exists
Tanzania
exists
Thailand
exists
Timor-Leste
NOT EXISTS
Togo
exists
Tonga
exists
Trinidad and Tobago
NOT EXISTS
Tunisia
NOT EXISTS
Turkiye
NOT EXISTS
Turkmenistan
NOT EXISTS
Uganda
exists
Ukraine
exists
United Arab Emirates
NOT EXISTS
United Kingdom
NOT EXISTS
United States
NOT EXISTS
Uruguay
exists
Uzbekistan
exists
Vanuatu
exists
Venezuela, RB
NOT EXISTS
Viet Nam
NOT EXISTS
Yemen, Rep.
NOT EXISTS
Zambia
NOT EXISTS
Zimbabwe
exists

### Save to perform network analysis

In [160]:
country_shared_kwds_filtered.to_csv("country_shared_kwds_filtered.csv", index=False)